<a href="https://colab.research.google.com/github/Magesh-Leo/Machine-Learning/blob/master/Mpg_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn import pipeline,preprocessing,metrics,model_selection,ensemble
from sklearn_pandas import DataFrameMapper
from sklearn.linear_model import LinearRegression

In [4]:
df=pd.read_csv('auto_mpg.csv')
df.head()

mpg  cylinders  displacement  ... model year  origin                   car name
0  18.0          8         307.0  ...         70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...         70       1          buick skylark 320
2  18.0          8         318.0  ...         70       1         plymouth satellite
3  16.0          8         304.0  ...         70       1              amc rebel sst
4  17.0          8         302.0  ...         70       1                ford torino

[5 rows x 9 columns]

In [5]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [6]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [7]:
mapper=DataFrameMapper([
                        (['cylinders', 'displacement','weight','acceleration', 'model year'],preprocessing.StandardScaler()),
                        (['origin'],preprocessing.OneHotEncoder())
])

In [50]:
mapper

DataFrameMapper(default=False, df_out=False,
                features=[(['cylinders', 'displacement', 'weight',
                            'acceleration', 'model year'],
                           StandardScaler(copy=True, with_mean=True,
                                          with_std=True)),
                          (['origin'],
                           OneHotEncoder(categories='auto', drop=None,
                                         dtype=<class 'numpy.float64'>,
                                         handle_unknown='error',
                                         sparse=True))],
                input_df=False, sparse=False)

In [51]:
pipeline_obj=pipeline.Pipeline([
                                ('mapper',mapper),
                                ('model',ensemble.RandomForestRegressor())

])

In [52]:
X=['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin']
y=['mpg']

In [53]:
pipeline_obj.fit(df[X],df[y])


/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py:354: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)


Pipeline(memory=None,
         steps=[('mapper',
                 DataFrameMapper(default=False, df_out=False,
                                 features=[(['cylinders', 'displacement',
                                             'weight', 'acceleration',
                                             'model year'],
                                            StandardScaler(copy=True,
                                                           with_mean=True,
                                                           with_std=True)),
                                           (['origin'],
                                            OneHotEncoder(categories='auto',
                                                          drop=None,
                                                          dtype=<class 'numpy.float64'>,
                                                          handle_unknown='error',
                                                          sparse=True))],
                

In [54]:
pipeline_obj.predict(df[X])

array([17.05 , 14.53 , 17.13 , 16.14 , 16.88 , 14.58 , 13.915, 14.23 ,
       13.455, 14.84 , 14.89 , 14.42 , 14.94 , 14.22 , 23.97 , 21.08 ,
       19.46 , 20.78 , 27.01 , 26.735, 24.525, 24.498, 24.95 , 25.42 ,
       20.76 , 10.4  , 10.56 , 11.75 ,  9.82 , 27.04 , 26.725, 24.852,
       26.525, 20.078, 16.823, 17.56 , 18.62 , 18.26 , 14.01 , 13.635,
       14.055, 14.23 , 12.26 , 12.92 , 12.68 , 18.4  , 21.831, 18.722,
       18.19 , 23.49 , 27.425, 29.6  , 29.239, 31.599, 32.955, 27.33 ,
       26.935, 24.257, 25.485, 22.81 , 20.661, 22.359, 13.49 , 13.615,
       14.59 , 13.895, 16.03 , 12.   , 12.66 , 12.38 , 13.205, 20.94 ,
       14.91 , 13.55 , 13.22 , 13.995, 19.12 , 22.27 , 20.641, 25.955,
       22.41 , 26.6  , 22.922, 26.93 , 27.02 , 13.5  , 14.47 , 13.35 ,
       14.06 , 14.645, 12.01 , 13.17 , 13.09 , 14.09 , 12.59 , 12.04 ,
       13.19 , 18.556, 16.25 , 18.41 , 17.835, 21.622, 26.285, 11.41 ,
       12.14 , 12.82 , 12.44 , 18.68 , 21.805, 20.881, 23.219, 21.874,
      

In [55]:
from sklearn.externals import joblib

In [56]:
joblib.dump(pipeline_obj,'RFMautompg.pkl')

['RFMautompg.pkl']

In [58]:
model_reload=joblib.load('RFMautompg.pkl')

In [59]:
model_reload.predict(df[X])

array([17.05 , 14.53 , 17.13 , 16.14 , 16.88 , 14.58 , 13.915, 14.23 ,
       13.455, 14.84 , 14.89 , 14.42 , 14.94 , 14.22 , 23.97 , 21.08 ,
       19.46 , 20.78 , 27.01 , 26.735, 24.525, 24.498, 24.95 , 25.42 ,
       20.76 , 10.4  , 10.56 , 11.75 ,  9.82 , 27.04 , 26.725, 24.852,
       26.525, 20.078, 16.823, 17.56 , 18.62 , 18.26 , 14.01 , 13.635,
       14.055, 14.23 , 12.26 , 12.92 , 12.68 , 18.4  , 21.831, 18.722,
       18.19 , 23.49 , 27.425, 29.6  , 29.239, 31.599, 32.955, 27.33 ,
       26.935, 24.257, 25.485, 22.81 , 20.661, 22.359, 13.49 , 13.615,
       14.59 , 13.895, 16.03 , 12.   , 12.66 , 12.38 , 13.205, 20.94 ,
       14.91 , 13.55 , 13.22 , 13.995, 19.12 , 22.27 , 20.641, 25.955,
       22.41 , 26.6  , 22.922, 26.93 , 27.02 , 13.5  , 14.47 , 13.35 ,
       14.06 , 14.645, 12.01 , 13.17 , 13.09 , 14.09 , 12.59 , 12.04 ,
       13.19 , 18.556, 16.25 , 18.41 , 17.835, 21.622, 26.285, 11.41 ,
       12.14 , 12.82 , 12.44 , 18.68 , 21.805, 20.881, 23.219, 21.874,
      

In [65]:
#X=['cylinders', 'displacement', 'horsepower', 'weight',
#       'acceleration', 'model year', 'origin']
temp={}
temp['cylinders']=1
temp['displacement']=2
temp['horsepower']=3
temp['weight']=4
temp['acceleration']=5
temp['model year']=6
temp['origin']=1

In [66]:
testdata=pd.DataFrame({'x':temp}).transpose()

In [67]:
testdata

acceleration  cylinders  displacement  ...  model year  origin  weight
x             5          1             2  ...           6       1       4

[1 rows x 7 columns]

In [68]:
model_reload.predict(testdata)[0]

27.941999999999997

In [8]:
pipeline_obj=pipeline.Pipeline([
                                ('mapper',mapper),
                                ('model',LinearRegression())

])
X=['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin']
y=['mpg']
pipeline_obj.fit(df[X],df[y])

Pipeline(memory=None,
         steps=[('mapper',
                 DataFrameMapper(default=False, df_out=False,
                                 features=[(['cylinders', 'displacement',
                                             'weight', 'acceleration',
                                             'model year'],
                                            StandardScaler(copy=True,
                                                           with_mean=True,
                                                           with_std=True)),
                                           (['origin'],
                                            OneHotEncoder(categories='auto',
                                                          drop=None,
                                                          dtype=<class 'numpy.float64'>,
                                                          handle_unknown='error',
                                                          sparse=True))],
                

In [9]:
pipeline_obj.score(df[X],df[y])

0.8239985496305645

In [10]:
from sklearn.externals import joblib
joblib.dump(pipeline_obj,'LRMautompg.pkl')
model_reload=joblib.load('LRMautompg.pkl')
model_reload.predict(df[X])

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


array([[14.75847058],
       [14.23058917],
       [15.32858404],
       [15.20841722],
       [14.81367801],
       [10.99149291],
       [11.27442501],
       [11.20051177],
       [10.93914042],
       [13.47671877],
       [15.64125413],
       [14.07403754],
       [14.49234714],
       [20.63433644],
       [23.52035892],
       [18.60072457],
       [19.04930064],
       [20.50338688],
       [24.85181209],
       [27.91707476],
       [21.66234062],
       [22.8781725 ],
       [23.68453068],
       [24.28180306],
       [19.88290905],
       [ 8.16207708],
       [ 8.91690767],
       [ 8.87250468],
       [ 6.8260795 ],
       [25.646209  ],
       [23.03820068],
       [25.19998522],
       [24.26970096],
       [21.16934823],
       [15.5845423 ],
       [16.9154917 ],
       [17.11098856],
       [16.82753118],
       [11.36753416],
       [10.51142614],
       [12.02327849],
       [11.65900989],
       [ 6.59283269],
       [ 8.54828033],
       [ 5.69547433],
       [19